[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
polymarket = "BEAARYAudpWhoLTmgCzt3Eh6afy5y6JjmPbBWLV3GifJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
